# NannyRadar Spec-Kit Configuration
project:
  name: "NannyRadar"
  version: "1.0.0"
  description: "Quantum-Enhanced Babysitting Platform with PhD-Level AI"

# CI/CD Gates
gates:
  docs:
    - markdownlint
    - spec-validation
  backend:
    - build
    - test
    - lint
  frontend:
    - build
    - test
    - lint

# Paths
paths:
  backend: "./backend"
  frontend: "./frontend"
  specs: "./.spec-kit/spec"
  plans: "./.spec-kit/plan"
  tasks: "./.spec-kit/tasks"
  prompts: "./.spec-kit/prompts"

# Validation Rules
validation:
  milestones:
    required_fields: ["id", "title", "description", "due_date", "status"]
  backlog:
    required_fields: ["id", "title", "description", "milestone", "priority", "status"]
  specs:
    required_files: ["00-PRD.md", "01-Architecture.md", "02-APIs.md", "03-Data-Model.md"]
